### ISSUE TITLE
Test failure with newest K

### ISSUE THREAD

**Issue by bmmoore** [kframework/c-semantics#119]
Testing b7099f5b2e37afcddf266bd8ac6babe1beaf91ea against kframework/k@425f4a45ba5e1d03db46b6e5bc4a61e7b11f226b fails one test in unit-fail, `j087a.c`

    $ cat j087a.out
    Error: CEE2
    Description: Referring to an object outside of its lifetime.
    Type: Undefined behavior.
    See also: C11 sec. 6.2.4
      at __va_inc(j087a.c:6)
      at f(j087a.c:6)
      at main(j087a.c:11)
      at <file-scope>(<unknown>)
    $ cat j087a.ref
    Error: EIO10
    Description: Type of lvalue not compatible with the effective type of the object being accessed.
    Type: Undefined behavior.
    See also: C11 sec. 6.5:7
      at f(j087a.c:6)
      at main(j087a.c:11)
      at <file-scope>(<unknown>

**Comment by dwightguth** [comment]
Yes, I'm aware of this issue, it seems to be a confluence bug; some rule orderings trigger it and others don't. I will fix it soon.

**Comment by dwightguth** [comment]
This bug seems to be really annoying. I'm not entirely sure what causes the non-confluence, but the correct behavior here should be to report undefined behavior when calling va_start. Cf. J.2:1 item 87, 6.9.1:8.

**Comment by dwightguth** [comment]
Can you look into this @chathhorn ?

**Comment by chathhorn** [comment]
Could you explain the symptoms a bit better? Do both errors appear in different circumstances?

Otherwise, it just looks like I should add another check in the rules for __va_start().

**Comment by dwightguth** [comment]
It seems to be a confluence issue. Depending on the rule ordering, both can
occur. I haven't tracked it down though.
