### ISSUE TITLE
semantics of *scanf?

### ISSUE THREAD

**Issue by edgar-pek** [kframework/c-semantics#124]
I could not find a semantics of *scanf functions. Are there some fundamental reasons why those are currently not supported?
I am asking because it would be cool if the semantics could handle examples below
https://sourceware.org/bugzilla/show_bug.cgi?id=12437
https://sourceware.org/bugzilla/show_bug.cgi?id=12701

**Comment by dwightguth** [comment]
We don't currently have a semantics for scanf, no. But you can access the glibc scanf function using the rv-match native call interpreter.

**Comment by chathhorn** [comment]
We do have semantics of *scanf now.
