### ISSUE TITLE
kcc on structs with no named members

### ISSUE THREAD

**Issue by msaxena2** [kframework/c-semantics#132]
Consider the program:
struct a{
    int : 5
};

int main() {
    printf("Execution");
}
Compiling this file with kcc, and then running it works fine, and "Execution" is printed to the screen. However, according C11 sec 6.7.2.1,  "A structure or union is defined as containing no named members" is undefined. Shouldn't kcc also be reporting undefined  behavior here?

**Comment by dwightguth** [comment]
This is something we need to fix, yes.
