### ISSUE TITLE
kcc on empty structs

### ISSUE THREAD

**Issue by msaxena2** [kframework/c-semantics#133]
Consider the program:
struct a{
};

int main() {
    printf("Execution");
}

kcc, when run on this file, reports undefined behavior,  with error code "CDT1" and the error message being "structs cannot be empty". C11 6.2.5:20 mentions that a struct is a "non empty set of member objects". Doesn't this actually define the behavior? Shouldn't kcc not report this as undefined behavior?

**Comment by dwightguth** [comment]
Closing this one. I think we are going to keep this as undefined behavior since that's what the section specific to struct declarators says it is.
