### ISSUE TITLE
test-build failing

### ISSUE THREAD

**Issue by bmmoore** [kframework/c-semantics#135]
The test-build target fails trying to run the test program because `-` is apparently no longer supported as the name of the input file:

    make[1]: Leaving directory '/home/brandon/code/k/c-semantics/semantics'
    Testing kcc...
    printf "#include <stdio.h>\nint main(void) {printf(\"x\"); return 42;}\n" | dist/kcc - -o dist/testProgram.compiled
    Unsupported option - at dist/kcc line 333.
    Makefile:65: recipe for target 'test-build' failed
    make: *** [test-build] Error 255

**Comment by dwightguth** [comment]
Fixed #130
