### ISSUE TITLE
Diamond in subsorting

### ISSUE THREAD

**Issue by bmmoore** [kframework/c-semantics#14]
Is there any reason to have the production

    syntax KItem ::= Type [avoid]

in `cil-exp.k`? The definition kompiles without it.

It would be nice if the CIL semantics works with the Coq backend, and to help that I'd like to label the injections into TypeOrExp, but doing it without removing that KItem production produces parsing ambiguities (maybe a bug, I opened kframework/k#589).

**Comment by dwightguth** [comment]
closing since we aren't really supporting CIL anymore
