### ISSUE TITLE
Effective type check for structs/union is backwards

### ISSUE THREAD

**Issue by dwightguth** [kframework/c-semantics#159]
So if you look at the C11 standard section 6.5 paragraphs 6 and 7, it says that an object with effective type E can be accessed by an lvalue with type L if (among other conditions) L is an aggregate or union type and one of its members has type L' which is type for which an lvalue in allowed to access an object with effective type E.

However, currently this check is backwards, we are checking that E is an aggregate type and one of its members E' is a type which, were it the effective type of an object, could be accessed via an lvalue of type L.

I tried to fix this but it turned out to be more complicated than I expected because simply reversing the order of the check generated a lot of false positives. They seem to arise in the case where getTypeAtOffset accepts an offset of 0 and therefore returns the aggregate type itself. This aggregate type is then used as the effective type of a write to a subobject of the struct with a different type, which causes an error to be raised. I'm not entirely sure what the correct solution is here, because strictly assigning the struct type as the effective type of an object of allocated duration that has been written to through an lvalue of struct type, would seem to mean that if I subsequently write to any member of that struct, it is undefined according to the aliasing rules. It's pretty clear that the interactions between aggregate/union types and effective type was not completely worked out properly by the standard, but I don't have the time to work out something reasonable for us to do in this case. I think what I would propose is to make the effective type of subobjects be the corresponding member type of the effective type of the parent object. So if I have a declared object of aggregate or union type, the effective type when accessing an entire aggregate or union would be the declared type, and when accessing a member would be the inner type of the member. And if I have a malloced object that has been given an effective type of an aggregate or union type, then when I read or write one of its members, we treat the effective type as the type of the member actually stored at that offset.

That way, when we call `#effectivelyCompat`, the effective type we pass it will never be an aggregate or union except in cases when the lvalue is also an aggregate or union.

This seems kind of tricky to handle though so I'm creating an issue for this and assigning it to @chathhorn . Chris, when you read this, if you want to discuss the issue or propose an alternate solution, let me know.

**Comment by chathhorn** [comment]
I don't think the issue is that the check is reversed, but rather that that particular exemption for aggregates/unions was missing. The fact that we can't tell whether the object at a certain offset is the aggregate or its first element is a separate issue.

**Comment by dwightguth** [comment]
Okay, so your proposal is:

* If the effective type is an aggregate, treat it as if it were the type of the element at that offset.
* If the effective type is a union, treat it as if it can validly be any of the members
* If the lvalue is an aggregate or a union, do exactly what the standard says in that case?

This seems roughly equivalent to what I had in mind.

**Comment by chathhorn** [comment]
Yeah. Although I was going to keep the original behavior where we first check for compatibility with the aggregate type before considering the type of its first element.

**Comment by dwightguth** [comment]
Sounds good
