### ISSUE TITLE
Error codes should be made uniform

### ISSUE THREAD

**Issue by grosu** [kframework/c-semantics#179]
@msaxena2 , as we discussed, the error codes of the C semantics should be made uniform.  For, they should all start with a capital letter.  Can you please go ahead and do this change as soon as you get a chance?

**Comment by dwightguth** [comment]
You mean the descriptions right? Codes are already all capitals. But if you mean descriptions, you should also normalize whether they end in a period

**Comment by grosu** [comment]
Yes, that's what I meant, @dwightguth.  And I agree with the period, too.  Several of our potential users asked us to show them the error codes, so people are actually really interested in seeing them.  It looks unprofessional to not follow uniform conventions.

**Comment by msaxena2** [comment]
Handled in #182 .
