### ISSUE TITLE
Syncing Examples and Error Codes

### ISSUE THREAD

**Issue by msaxena2** [kframework/c-semantics#183]
Currently, the Error Codes CSV is modified manually when any change to the semantics is made. This process is error prone, and may lead to the CSV being out of sync with the examples, and the semantics. We need some way of automatically generating the CSV from the semantics, and then checking if all the error codes have corresponding examples in the examples directory. Additionally we may want to then run the examples, check if they produce the required error, and update the output files.

**Comment by dwightguth** [comment]
The first step will be to generate tests to run all the examples on every merge and pull request. Then we can ensure that the example outputs and the outputs of the programs when run are in sync. Then we can write a simple bash script that parses all the output files to generate the CSV.

**Comment by msaxena2** [comment]
Fixed using the maven code plugin.
