### ISSUE TITLE
spell-check error messages

### ISSUE THREAD

**Issue by grosu** [kframework/c-semantics#201]
See, for example, "Implementiation" in the error message below:
```
Error: IMPL-CCV2
Description: conversion to signed integer outside the range that can be represented.
Type: Implementiation defined behavior.
See also: C11 sec. 6.3.1.3:3, J.3.5:1 item 4
  at main(6-int-overflow.c:5)
  at <file-scope>(<unknown>)
```

**Comment by grosu** [comment]
And also, haven't we decided to start all the descriptions with capital letters?

**Comment by dwightguth** [comment]
Capital letter is fixed in my copy. Can you tell me where you got your copy that's not fixed?

Spell checking is now included in my latest diff that should hopefully be live sometime tomorrow.

**Comment by grosu** [comment]
from vagrant, yesterday.

**Comment by dwightguth** [comment]
@grosu I'm going to  close this because I did a spell check and these issues seem to be fixed but feel free to reopen if you see something new.
