### ISSUE TITLE
Fix Robby's program

### ISSUE THREAD

**Issue by dwightguth** [kframework/c-semantics#211]
This program should be undefined:

```
 #include <stdio.h>

 unsigned long f() {
  double d = -0.5;
  return d * (1 << 30);
 }
 int main() {
  printf("0x%lx\n",f());
 }
```

**Comment by chathhorn** [comment]
This appears to be a bug in mlgmp. Apparently the semantics of mpfr_get_z_exp were changed from it returning an unsigned mantissa to a signed mantissa, but mlgmp (gmp.ml:631) is still negating it.

I guess the solution is just to negate it in prelude.ml -- mlgmp doesn't appear to be maintained.

**Comment by dwightguth** [comment]
@chathhorn actually we are maintaining some changes to mlgmp so I think probably the thing to do is to modify that patch. I suggest you download MLGMP, apply the patch here: https://github.com/kframework/k/blob/master/k-distribution/src/main/scripts/lib/opam/packages/mlgmp/mlgmp.20150824/files/patch, and then make the modification to the C file and recreate the patch. Then you should create a pull request for K.
