### ISSUE TITLE
Issue with K version 3.6 and Ocaml 4.03.0+k and oasis package

### ISSUE THREAD

**Issue by francesco-bongiovanni** [kframework/c-semantics#229]
@ellisonch @cos 

Hi Chucky and Cosmin, 

I am trying to install the c-semantics but keep having an issue when I do the k-configure-opam-dev. 

It's trying to install the oasis package but I got the following error: 

The following dependencies couldn't be met:
  - mlgmp -> oasis
Your request can't be satisfied:
  - oasis is not available because your system doesn't comply with ocaml-version >= "3.11.2" & ocaml-version < "4.03.0".

Am I doing something wrong ?

Thanks for the reply ! 

and congrats for the work behind K ! its truly awesome !!!

**Comment by dwightguth** [comment]
The install instructions were unfortunately out of date. Can you please take a look at the updated install instructions in #234 and try to follow them and let me know if there are any issues? If so, I will try to update them further, if not, I will merge the new instructions and you will have a working installation.

**Comment by dwightguth** [comment]
FYI: @ellisonch and @cos aren't really doing active development on the C semantics right now... It's mostly me and @chathhorn

**Comment by francesco-bongiovanni** [comment]
Hi @dwightguth , I  manage to install  it and it seems to work, I got passed the k-configure-opam-dev. Thanks for your help !
