### ISSUE TITLE
illegal quoting in errors file

### ISSUE THREAD

**Issue by grosu** [kframework/c-semantics#253]
https://github.com/kframework/c-semantics/blob/master/examples/error-codes/Error_Codes.csv#L102

How comes we have this error, and how comes everything works with it?

**Comment by dwightguth** [comment]
@msaxena2 is it possible we could add an addendum to the maven plugin that reports an error if the csv file doesn't parse cleanly?

**Comment by msaxena2** [comment]
Not sure what's happening here since the csv parsing library should've thrown an error. I'm looking into it.

**Comment by dwightguth** [comment]
My guess is it's treating unmatched quotes as if they are literal quote characters. Is there a way to configure that?

**Comment by msaxena2** [comment]
fixed via runtimeverification/error-codes-mvn-plugin#3
