### ISSUE TITLE
Build errors in c-semantics on 'make -j4'

### ISSUE THREAD

**Issue by farazhussain** [kframework/c-semantics#256]
I get these llvm/clang related build errors when 'make'ing, although I did follow all the install instructions. I will appreciate if you can have a look and tell me what I'm doing wrong.

[merrors.20sep2016.txt](https://github.com/kframework/c-semantics/files/483494/merrors.20sep2016.txt)

**Comment by dwightguth** [comment]
It's hard for me to debug without more info. How did you install llvm and clang 3.6? what OS version are you using?

**Comment by farazhussain** [comment]
Thanks!

OS: Linux machine1 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I was following the instructions here (https://github.com/kframework/c-semantics/blob/master/INSTALL.md), so I installed libclang-3.6-dev with apt-get.

**Comment by dwightguth** [comment]
Okay, if this is ubuntu, can I see an `lsb_release -a`?

**Comment by farazhussain** [comment]
fhussain@machine1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
fhussain@machine1:~$

**Comment by dwightguth** [comment]
I don't really know what's going wrong here... this is the exact same release I have and you're following instructions I've tested. Something seems to be wrong with the way your llvm is configured, because it appears to be missing some macros that should be defined. Are you sure you also installed llvm 3.6 from the Ubuntu 16.04 repo? the macro you seem to be missing in the first error listed is defined in /usr/lib/llvm-3.6/include/llvm/Support/Compiler.h. You might ask yourself why that header isn't getting included correctly.

**Comment by farazhussain** [comment]
Thank you so much.   The instructions told me to install libclang-3.6-dev, so that's exactly what I did. Likewise for the other packages. Maybe I need some other llvm package that's missing. 

This is what happens on executing the first line from the instructions:

fhussain@machine1:~$ sudo apt-get install maven git openjdk-8-jdk flex libgmp-dev libmpfr-dev build-essential cmake zlib1g-dev libclang-3.6-dev diffutils libxml-libxml-perl libstring-escape-perl libgetopt-declare-perl 
[sudo] password for fhussain: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
diffutils is already the newest version (1:3.3-3).
flex is already the newest version (2.6.0-11).
git is already the newest version (1:2.7.4-0ubuntu1).
libgmp-dev is already the newest version (2:6.1.0+dfsg-2).
libmpfr-dev is already the newest version (3.1.4-1).
libxml-libxml-perl is already the newest version (2.0123+dfsg-1build1).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4).
libclang-3.6-dev is already the newest version (1:3.6.2-3ubuntu2).
libgetopt-declare-perl is already the newest version (1.14-1).
libstring-escape-perl is already the newest version (2010.002-1).
maven is already the newest version (3.3.9-3).
cmake is already the newest version (3.5.1-1ubuntu2).
openjdk-8-jdk is already the newest version (8u91-b14-3ubuntu1~16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by farazhussain** [comment]
I found the problem: need to install package llvm-3.6 (this includes llvm-3.6-dev and llvm-3.6-runtime).  

Many thanks!
