### ISSUE TITLE
kcc error about missing class

### ISSUE THREAD

**Issue by farazhussain** [kframework/c-semantics#257]
On Ubuntu 16.04 (64bit), I get the following message:

fhussain@machine1:~/repos/research/fpcsmith/fpbugshome/bug1$ kcc -d -I${CSMITH_HOME}/runtime wrong1.c 
'/home/fhussain/repos/research/c-semantics/dist/x86-gcc-limited-libc/pp' '-I' '/home/fhussain/repos/research/fpcsmith/runtime' '-pedantic' 'wrong1.c' '-o' 'tmp-kcc-mJ9kxLC'
/home/fhussain/repos/research/c-semantics/dist/cparser tmp-kcc-mJ9kxLC --trueName 'wrong1.c' > tmp-kcc-wDXoODW
'krun' '--output' 'binary' '--output-file' 'tmp-kcc-oHO79iI' '-d' '/home/fhussain/repos/research/c-semantics/dist/x86-gcc-limited-libc/c11-translation-kompiled' '-w' 'none' '--smt' 'none' '--debug' '--interpret' '-cOPTIONS=`_Set_`(`SetItem`(`NoLink`(.KList)), `.Set`(.KList)) ' '-pOPTIONS=printf %s' '-pOBJS=printf %s' '-cOBJS=.K' '--parser' 'cat' 'tmp-kcc-wDXoODW'
File: /home/fhussain/repos/research/fpcsmith/runtime/safe_math.h
Line: 301
Error: UB-CEB12
Description: Potential negative zero produced via bitwise operations (this could be a false positive).
Type: Undefined behavior.
See also: C11 sec. 6.2.6.2:4, J.2:1 item 14
Error: Could not find or load main class org.kframework.main.BinaryToText
Translation failed (config dumped). Refer to last command run for details.

Did I miss a classpath somewhere?  I do have the class file:

fhussain@machine1:~/repos/research/k$ find . -name "BinaryToText*"
./kernel/target/classes/org/kframework/main/BinaryToText.class
./kernel/src/main/java/org/kframework/main/BinaryToText.java

Thanks.

**Comment by dwightguth** [comment]
Oh, that's a bug. It has to do with the way we're dumping configurations when a program fails. You should be able to fix it by enabling the kserver, which will conveniently also make kcc much faster. You do this by running the "kserver" command in another window while the kframework is in your path.

I am in meetings for the rest of the day but I will fix this tomorrow, and it will probably go live on Friday.

**Comment by farazhussain** [comment]
Thanks! On enabling the kserver and compiling, the message about the missing class is gone, but I still get translation failed. I'm guessing it didn't generate the binary because kcc determined that this program has undefined behavior?

**Comment by dwightguth** [comment]
That's correct. The open source version of the C semantics cannot recover
from errors: if your program has undefined behavior, it will report the
error and then stop.

**Comment by farazhussain** [comment]
Thanks!
