### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by JerryWang304** [kframework/c-semantics#260]
I want to install it on my mac. After typing "make -j4", there is error:  'clang/AST/ASTConsumer.h' file not found
#include "clang/AST/ASTConsumer.h"

Any one can solve that problem?

**Comment by dwightguth** [comment]
You have a couple choices:

1. If you want to compile without the experimental and incomplete C++ semantics, you can just comment out line 22 of the Makefile.

2. If you want to build the C++ semantics as well, you need to install clang 3.6 on your machine to the /usr/lib/llvm-3.6 directory.

**Comment by wxie2017** [comment]
Hi, @dwightguth 

1. If you want to compile without the experimental and incomplete C++ semantics, you can just comment out line 22 of the Makefile. 
Do you mean to comment out this line?
$(SCRIPTS_DIR)/program-runner \

2. If you want to build the C++ semantics as well, you need to install clang 3.6 on your machine to the /usr/lib/llvm-3.6 directory.
This is not working with clang 3.8/3.9/4.0.
Is there a fix for it?

best regards,
wxie

**Comment by dwightguth** [comment]
hi, sorry, the line numbers changed. I am referring to this line:

```
$(CPPPARSER_DIR)/clang-kast \
```

If you do a git pull, you should be able to get it to work now with clang 3.9, since we updated the clang version we were using a couple days ago.

**Comment by wxie2017** [comment]
Thanks, @dwightguth : with new git pull, building C++ parser is still not working with clang 3.9.

**Comment by dwightguth** [comment]
can you tell me what error you're getting? the latest version of the C semantics should build the C++ parser with clang 3.9 if you have the necessary libraries installed to /usr/lib/llvm-3.9
