### ISSUE TITLE
Result of relational operators does not have type 'bool'

### ISSUE THREAD

**Issue by h0nzZik** [kframework/c-semantics#267]
In semantics/cpp14/language/translation/expr/relational.k, there are some rules like [this one](https://github.com/kframework/c-semantics/blob/master/semantics/cpp14/language/translation/expr/relational.k#L8-L9):

```
     rule R1:PRVal == R2:PRVal
          => pre(stripHold(R1) == stripHold(R2), combine(...), type(R1))
```

I suppose there should be `type(bool)` on rhs. For example, the following program
```
int x = 1;
if (true == (x == 2))
    ;
```
fails in runtime. I can create pull request if you agree this is a bug.

**Comment by dwightguth** [comment]
Yes, you are right, that is a bug.
