### ISSUE TITLE
What is the purpose of `unknown()` in C++ semantics?

### ISSUE THREAD

**Issue by h0nzZik** [kframework/c-semantics#274]
In https://github.com/kframework/c-semantics/blob/master/semantics/cpp14/language/common/expr/cast.k#L65-L66,
```
rule inverseConvertType(T:CPPIntegerType, prv(C::CPPValue, Tr::Trace, T':CPPScopedEnumType))
         => prv(unknown(C), Tr, T)
```
why we do not just use UNSPEC according to 5.2.9:9? This rule may cause problems when the resulting prv() is used. In this example
```
enum class M : int { Val = 10000 };
int main() {
    char m = (char)M::Val;
    //int m = (int)(char)M::Val;
}
```
the static semantics halts on
```
inRangeCpp(unknown(#token("10000","Int")),tcpp(quals(`.Set`(.KList)),`.Set`(.KList),`char_CPP-TYPING-SYNTAX`(.KList)))
```
What is the purpose of `unknown`?

**Comment by dwightguth** [comment]
I guess we could use UNSPEC. Generally the idea behind the unknown klabel is that unknown represents an unspecified value and UNSPEC represents an unspecified behavior. We report the former behavior as UNSPEC when it affects the behavior of the program (ie if we compare an unspecified value, write it as output, or return it from the main function.

@chathhorn do you have thoughts on this?

**Comment by chathhorn** [comment]
Yeah, in C at least I think it's mostly meant to serve the purpose of an indeterminate value that can't be a trap. It should be perfectly specified/defined to copy uninitialized automatic duration objects via unsigned char* or memcpy, for example, but the actual values copied are "unknown."

**Comment by h0nzZik** [comment]
So I will keep it as it is and just make sure that `m` in the example ends up with an `unknown` value.
