### ISSUE TITLE
make -j4 error for linux

### ISSUE THREAD

**Issue by wxie2017** [kframework/c-semantics#285]
output:
Makefile:31: recipe for target 'x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp] Error 113
Makefile:112: recipe for target 'execution-semantics' failed

**Comment by dwightguth** [comment]
Hi, sorry, I need a more complete build log than that. Can you show the output from running the `kompile` command?

**Comment by wxie2017** [comment]
Hi, @dwightguth 
I am not sure what you need. I build only c parser. I extract the error part:

/tmp/tmp-kompile-8253915954909945985.l:2396: warning, rule cannot be matched
/tmp/tmp-kompile-1000737434543300846.l:2396: warning, rule cannot be matched
/tmp/tmp-kompile-3320294487404708339.l:2396: warning, rule cannot be matched
/tmp/tmp-kompile-7334834515914944657.l:19732: warning, rule cannot be matched
/tmp/tmp-kompile-7904794785731604832.l:13693: warning, rule cannot be matched
/tmp/tmp-kompile-3244058543594566385.l:17103: warning, rule cannot be matched
/tmp/tmp-kompile-5052764398173822029.l:41072: warning, rule cannot be matched
/tmp/tmp-kompile-8962163280997564001.l:53689: warning, rule cannot be matched
/tmp/tmp-kompile-1189291787224471788.l:59343: warning, rule cannot be matched
	org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 59 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:164)
	at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:139)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:157)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Had 59 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(10,23,10,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(11,23,11,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(12,25,12,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(14,24,14,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(15,24,15,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(16,24,16,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(18,24,18,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(19,23,19,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(20,24,20,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(21,23,21,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(22,24,22,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(26,24,26,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(27,24,27,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(28,24,28,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(29,23,29,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(30,24,30,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(32,23,32,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(33,24,33,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(34,23,34,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(35,22,35,23)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(36,24,36,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(37,25,37,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(39,24,39,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(40,24,40,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(41,27,41,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(43,29,43,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(44,27,44,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(45,26,45,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(46,30,46,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(47,26,47,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(48,28,48,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(49,29,49,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(5,23,5,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(50,33,50,34)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(51,33,51,34)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(52,28,52,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(53,30,53,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(54,30,54,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(55,28,55,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(56,31,56,32)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(57,26,57,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(58,29,58,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(59,27,59,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(60,30,60,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(61,28,61,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(62,25,62,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(63,25,63,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(64,26,64,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(65,27,65,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(66,30,66,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(67,27,67,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(68,30,68,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(69,27,69,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(7,23,7,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(70,30,70,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(71,26,71,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(72,29,72,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(8,23,8,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(9,21,9,22)
Makefile:31: recipe for target 'x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp] Error 113
make[1]: Leaving directory '/root/work/c-semantics/semantics'
Makefile:112: recipe for target 'execution-semantics' failed
make: *** [execution-semantics] Error 2
make: *** Waiting for unfinished jobs....
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 59 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:164)
	at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:139)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:157)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Had 59 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(10,23,10,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(11,23,11,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(12,25,12,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(14,24,14,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(15,24,15,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(16,24,16,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(18,24,18,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(19,23,19,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(20,24,20,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(21,23,21,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(22,24,22,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(26,24,26,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(27,24,27,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(28,24,28,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(29,23,29,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(30,24,30,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(32,23,32,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(33,24,33,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(34,23,34,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(35,22,35,23)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(36,24,36,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(37,25,37,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(39,24,39,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(40,24,40,25)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(41,27,41,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(43,29,43,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(44,27,44,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(45,26,45,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(46,30,46,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(47,26,47,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(48,28,48,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(49,29,49,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(5,23,5,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(50,33,50,34)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(51,33,51,34)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(52,28,52,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(53,30,53,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(54,30,54,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(55,28,55,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(56,31,56,32)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(57,26,57,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(58,29,58,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(59,27,59,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(60,30,60,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(61,28,61,29)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(62,25,62,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(63,25,63,26)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(64,26,64,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(65,27,65,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(66,30,66,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(67,27,67,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(68,30,68,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(69,27,69,28)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(7,23,7,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(70,30,70,31)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(71,26,71,27)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(72,29,72,30)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(8,23,8,24)
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/root/work/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
	Location(9,21,9,22)
Makefile:23: recipe for target 'x86-gcc-limited-libc/c11-translation-kompiled/c11-translation-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/c11-translation-kompiled/c11-translation-kompiled/timestamp] Error 113
make[1]: Leaving directory '/root/work/c-semantics/semantics'
Makefile:109: recipe for target 'translation-semantics' failed
make: *** [translation-semantics] Error 2

I think later the dist is build, and some programs are ok there. However, what are thest error?

best regards,
wxie

**Comment by wxie2017** [comment]
Hi, @dwightguth:

Is there anything else you need for tracking this error?

best regards,
wxie

**Comment by dwightguth** [comment]
Can you try rebuilding with the latest version of K and the C semantics?
