### ISSUE TITLE
 some questions about application (debug & state space search)

### ISSUE THREAD

**Issue by dexter-qjq** [kframework/c-semantics#300]
**i read the paper "a formal semantics of c whit application" ,and tried to do some examples about application mentioned in the paper.
 DEBUG:
 i just followed the description in it  and set the function "__debug()" . however, if i did not declare the function "__debug()"  its warning like this** 
debug.c: In function ‘main’:
debug.c:10:4: warning: implicit declaration of function ‘__debug’ [-Wimplicit-function-declaration]
    __debug(i);
    ^

**and if i tried to declare it like 
void __debug( int i ) {}** 
the kcc hits "debug.c:3:1: warning: Multiple external definitions for __debug. (Undefined behavior)"
**did the function "__debug" has been included some file that i need to include ahead?**

**state space search
a)
when i tried to explore  evaluation order :**
int r = 0 ;
int f (int x ) {return (r= x;)}
int main(void) {f(1) + f(2);  printf('%d",r); return 0;}

**the normal execution result is  2. and i should be two possible result in my mind : 1 and 2. 
the execution with option SEARCH=1 ./a.out** 

dexter@dexter-virtual-machine:~/Desktop/c-semantics/output$ kcc search.c 
Can't exec "rv-ifdefclear": No such file or directory at /home/dexter/Desktop/c-semantics/dist/kcc line 4002.
dexter@dexter-virtual-machine:~/Desktop/c-semantics/output$ ./a.out  
2
dexter@dexter-virtual-machine:~/Desktop/c-semantics/output$ SEARCH=1 ./a.out  
Searching reachable states... (with non-deterministic expression sequencing)
[Error] Critical: Can only specify option --directory once. (Can only specify
option --directory once.)
Error: Execution failed.

**b)
i don't know how to use #pragam to write and name LTL formula when model checking.
can you give me a specific example.**

the formula named safety is " [] ((lightNS == red) \/ (lightEW == red)) "
typedef enum {green, yellow, red} state ;
state lightNS=green;
state lightEW=red;

int changeNS()
{
switch(lightNS)
{ case(green)  : lightNS = yellow ; return 0;
case(yellow) : lightNS = red    ; return 0;
case(red)    : 
if (lightEW == red)
{
lightNS = green;
}
return 0 ;
}
}

int changeEW()
{
switch(lightEW)
{ case(green)  : lightEW = yellow ; return 0;
case(yellow) : lightEW = red    ; return 0;
case(red)    :
if(lightNS == red)
{ 
lightEW = green ;
}
return 0 ;
}
}

int main(void)
{ 
int i = 10 ;
while (1)
{
int x ;
x = changeEW() + changeNS() ;
//printf("%2d\n" , x) ;
//i -- ;
}
return 0;
}

**Comment by dwightguth** [comment]
This functionality is not supported in the current version of the C semantics. If you want to use it, you are going to have to find an old revision of kframework/k and the C semantics in order to test with. Try searching around in the versions that existed at the time of publication of that paper.

**Comment by dexter-qjq** [comment]
**i have successfully installed the c-semantics-3.4  and k-3.4 downloaded from github
and when i tried to do some tests about application above 
state search and LTL both have some unexpected results as below:** 

dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ kcc -s undefComma.c 
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ SEARCH=1 ./a.out 
Searching reachable states... (with non-deterministic expression sequencing)
========================================================================
1 solutions found
------------------------------------------------------------------------
Solution 1
Program got stuck
File: 
Line: 
Output:

========================================================================
1 solutions found

Generated kcc-search-results.dot.
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ kcc -s ../ltlmc/bad.c  -o bad
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ LTLMC="[]Ltl ~Ltl __error" ./bad
LTL model checking... (with non-deterministic expression sequencing)
[Error] Critical: Cannot retrieve file content. Make sure that file: ~Ltl
exists.
	File: internal
	Location: FileUtil.java

**Comment by dexter-qjq** [comment]
i've installed the c-semantics-3.4 and k-3.4 downloaded from github.
when i test some examples with applications , some errors including state space search and LTL model checking 

my java version is 
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)


the error log as below 
Generated kcc-search-results.dot.
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ kcc  undefComma.c 
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ SEARCH=1 ./a.out 
Searching reachable states... (with non-deterministic expression sequencing)
========================================================================
1 solutions found
------------------------------------------------------------------------
Solution 1
Program got stuck
File: 
Line: 
Output:

========================================================================
1 solutions found

Generated kcc-search-results.dot.
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ kcc -s ../ltlmc/bad.c  -o bad
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ LTLMC="[]Ltl ~Ltl __error" ./bad
LTL model checking... (with non-deterministic expression sequencing)
[Error] Critical: Cannot retrieve file content. Make sure that file: ~Ltl
exists.
	File: internal
	Location: FileUtil.java
dexter@dexter-virtual-machine:~/Desktop/C2/c-semantics-3.4.0/examples/search$ LTLMC="<>Ltl y == 2" ./bad
LTL model checking... (with non-deterministic expression sequencing)
[Error] Critical: Cannot retrieve file content. Make sure that file: == exists.
	File: internal
	Location: FileUtil.java
