### ISSUE TITLE
How to start learning  the K framework

### ISSUE THREAD

**Issue by dongbiao830415** [kframework/c-semantics#303]
1、I want to understand the details of  the K framework implementation, But I don't know how to start. Who can provide relevant information?
2、Symbolic Rewriting is used in  the K framework and what is the principle  of Symbolic Rewriting ?

Thank you very much!

**Comment by h0nzZik** [comment]
I would start with the [K Tutorial](http://www.kframework.org/index.php/K_Tutorial).
