### ISSUE TITLE
what is the execution process of a C program by kcc?

### ISSUE THREAD

**Issue by dexter-qjq** [kframework/c-semantics#304]
run with the command" -- kcc hellowrld.c -d“ 
and the final configuration saved to temp-kcc-conf-pretty-*.txt 
what does the final configuration mean ? is it the result of the static semantics? or the initializing configuration of execution ?
what is the exact meaning of the translation unit? every file used in a C program has a translation unit ,and what the use it is ?

**Comment by h0nzZik** [comment]
I do not understand this question. What are you referring to?

**Comment by dexter-qjq** [comment]
what is the use of the semantic/language/translation and ../execution respectively？

**Comment by h0nzZik** [comment]
It is described there: http://fsl.cs.illinois.edu/index.php/Defining_the_Undefinedness_of_C
