### ISSUE TITLE
Some problems of kcc and k

### ISSUE THREAD

**Issue by dongbiao830415** [kframework/c-semantics#305]
1、Can i run a simple K file on the runtimeverification K framework?
2、Does KCC not support the pthread* functions at the moment?
3、run kcc *.c , warning:
    Can't exec "rv-ifdefclear": No such file or directory at /root/src/c-semantics/c-semantics/dist/kcc line 4038.
4、kcc didn't detect the int overflow in the c-semantics/examples/c/demo/8-int-overflow-tricky.c file

**Comment by h0nzZik** [comment]
Ad 1. Yes, you can, but you have to `kompile -O2` and the configuration have to contain a cell with an "exit" attribute (like `<ret exit="">0</ret>`).

**Comment by dongbiao830415** [comment]
My version has included this modification

**Comment by dongbiao830415** [comment]
1、 kompile -O2 lambda.k ===>oK
module LAMBDA
  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
**configuration   <ret exit="">0</ret>            //I added**
endmodule
2、 kast ./tests/identity.lambda    ===>oK

output:
`lambda_.__LAMBDA`(#token("x","Id"),#token("x","Id"))
3、 krun ./tests/identity.lambda    ===>fail
output:
Fatal error: exception Invalid_argument("normalize0")
[Error] Critical: Failed to execute program in ocaml. See output for error
information.

why? Does krun lack any parameters?
