### ISSUE TITLE
kcc doesn't handle LL_APPEND

### ISSUE THREAD

**Issue by husbd** [kframework/c-semantics#323]
You can reproduce the problem like this:
```
git clone https://github.com/shijieg2/KCC-bug-samples.git
cd KCC-bug-samples/sample1
bash make.sh
```
This issue is the minimized version of the previous issue

**Comment by chathhorn** [comment]
This seems to be caused by `kcc` lacking a `__typeof` builtin (vs the `__typeof__` form, which we do define).
