### ISSUE TITLE
kcc can't compile FFmpeg

### ISSUE THREAD

**Issue by Lycbel** [kframework/c-semantics#325]
#kcc can't compile ff-mpeg and for the first error:
#XXXXXXXX wrong error rax.c[202:16-23] : syntax error Translation failed (kcc_config dumped).<------
#------>error should be Translation failed. To repeat.....
#I created a minimized input to reproduce it 
wget https://raw.githubusercontent.com/Lycbel/cs510Files/master/report4/report_ffmpeg/report.sh
bash report.sh

**Comment by chathhorn** [comment]
I assume this is the same issue as the redis issue? What's at `rax.c[202:16-23]`?

**Comment by Lycbel** [comment]
sorry I copied the wrong error the error should be Translation failed.
the cause should be:
#include <stdatomic.h>
if I include it gcc can work but kcc can't

**Comment by Lycbel** [comment]
moved to https://github.com/kframework/c-semantics/issues/346
