### ISSUE TITLE
kcc can't compile redis

### ISSUE THREAD

**Issue by Lycbel** [kframework/c-semantics#327]
kcc can't compile the C project redis, for the first error:
```rax.c[202:16-23] : syntax error Translation failed (kcc_config dumped).```
I created the minimized input to reproduce it. You can run the following command
```if [ -f "run.sh" ];then
rm run.sh
fi
wget https://raw.githubusercontent.com/Lycbel/cs510Files/master/report4/report_redis/run.sh
bash run.sh
```
#the error output file for compiling the whole redis project can be found : https://github.com/Lycbel/cs510Files/blob/master/report4/rebuild_totals/redis_error_output

**Comment by chathhorn** [comment]
Could you please include whatever is at `rax.c[202:16-23]`?

**Comment by Lycbel** [comment]
rax.c[202:16-23] is rax *rax = rax_malloc(sizeof(*rax));

I also created a .c file to regenerate the error which is:

include <stdlib.h>
void *rax_malloc(size_t size) {
    void *ptr = malloc(size);
    return (char*)ptr+10;
}

typedef struct raxNode {
} rax;
int main(){
//---------------here will have the same error---------------------------
rax *rax = rax_malloc(sizeof(*rax)); 
return 1;
}

**Comment by Lycbel** [comment]
this can be solved by replace rax by another name. but maybe -frecover-all-errors flag can force kcc pass this kind of code
