### ISSUE TITLE
if include stdatomic.h , kcc will have Translation failed error

### ISSUE THREAD

**Issue by Lycbel** [kframework/c-semantics#346]
if have 
``#include <stdatomic.h>``
when compile, kcc will have error of 
``Translation failed (kcc_config dumped). To repeat, run this command in directory``
to regenerate:
```
wget https://raw.githubusercontent.com/Lycbel/cs510Files/master/report4/report_ffmpeg/report.sh
bash report.sh
```

**Comment by chathhorn** [comment]
Should be fixed in the latest version of rv-match. Reopen if not.
