### ISSUE TITLE
locsWritten cell

### ISSUE THREAD

**Issue by bsorav** [kframework/c-semantics#526]
The "Defining the undefinedness of C" alludes to a locsWritten cell meant to catch undefined behaviour arising out of unspecified order of evaluation.  I tried looking for it but could not find anything similar in the code.  Would you be able to either point me to the right place in the code, or clarify if this is not available in the published code. Thanks.

**Comment by chathhorn** [comment]
The `locs-written` cell appears in the configuration here:
https://github.com/kframework/c-semantics/blob/50633cd9440273ac81f3db22ee28812e83196302/semantics/common/execution/thread_local.k#L92

Addresses are added to it here during i/o:
https://github.com/kframework/c-semantics/blob/50633cd9440273ac81f3db22ee28812e83196302/semantics/c/language/execution/io.k#L51

And it's cleared when we reach a sequence point here:
https://github.com/kframework/c-semantics/blob/50633cd9440273ac81f3db22ee28812e83196302/semantics/c/language/execution/sequence-point.k#L12

Let me know if you have any questions about it!

**Comment by bsorav** [comment]
Thanks Chris, this very helpful!
