### ISSUE TITLE
Deviation from Norrish's semantics for the simple assignment operator

### ISSUE THREAD

**Issue by bsorav** [kframework/c-semantics#580]
Hi,

I am looking at the semantics for the simple assignment operator in C encoded at:

https://github.com/kframework/c-semantics/blob/master/semantics/c/language/translation/expr/assignment.k

and comparing them to Norrish's semantics for the assignment operator :

https://www.researchgate.net/publication/2539225_An_abstract_dynamic_semantics_for_C

I notice a subtle deviation. While Norrish converts a simple assignment to a compound assignment with a special \diamond operator (representing the replacement operator), K framework's semantics model the simple assignment operator separately.  This leads to a subtle difference in the two behaviours: while Norrish's handling of the simple assignment involves read-modify-write (where the modification involves simple replacement), K-framework's semantics involve a single write.

We were wondering if this is a deliberate deviation?

Thanks a lot.

Sorav

**Comment by chathhorn** [comment]
Hi Sorav,

I'm pretty certain it's not a deliberate deviation from Norrish's semantics. I think it was just an attempt to adhere closer to the standard, which describes compound assignment in terms of simple assignment, and not the other way around.

**Comment by bsorav** [comment]
Hi Chris,

Thanks very much for clarification.
